name: Minify and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Minifiers
        run: npm install -g clean-css-cli terser html-minifier

      - name: Minify Process
        run: |
          mkdir dist
          # Copy isi dari DALAM folder src ke folder dist
          cp -r src/* dist/ 2>/dev/null || true

          # Proses Minify file yang sudah dipindah ke dist
          find dist -name "*.css" -exec cleancss -o {} {} \;
          find dist -name "*.js" -exec terser {} -o {} \;
          find dist -name "*.html" -exec html-minifier --collapse-whitespace --remove-comments -o {} {} \;

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
