name: Minify and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Minifiers
        run: npm install -g clean-css-cli terser html-minifier

      - name: Minify Process
        run: |
          mkdir dist
          cp -r * dist/ 2>/dev/null || true
          rm -rf dist/.github

          # Minify CSS
          find dist -name "*.css" -exec cleancss -o {} {} \;
          
          # Minify JS
          find dist -name "*.js" -exec terser {} -o {} \;
          
          # Minify HTML (Versi Aggressive: Hapus semua spasi & line break)
          find dist -name "*.html" -exec html-minifier \
            --collapse-whitespace \
            --remove-comments \
            --remove-redundant-attributes \
            --use-short-doctype \
            --remove-empty-attributes \
            --minify-js true \
            --minify-css true \
            -o {} {} \;

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
